name: fedimint-dev
root: .
socket_name: fedimint-dev
pre_window:
  - source .tmpenv
  - alias lightning-cli="\$FM_LIGHTNING_CLI"
  - alias lncli="\$FM_LNCLI"
  - alias bitcoin-cli="\$FM_BTC_CLIENT"
  - alias fedimint-cli="\$FM_MINT_CLIENT"
  - alias gwcli-cln="\$FM_GWCLI_CLN"
  - alias gwcli-lnd="\$FM_GWCLI_LND"
  - alias mint_rpc_client="\$FM_MINT_RPC_CLIENT"
  - alias dbtool="\$FM_DB_TOOL"
  - alias restart="./scripts/restart-tmux.sh"
  - source scripts/lib.sh
tmux_detached: false
windows:
  - main:
      panes:
        - user:
            - run_dkg
            - source scripts/tmux-user-shell.sh
  - gateways/bitcoind:
      panes:
        - user:
          - # empty user shell
        - bitcoind:
          - start_bitcoind &
          - fg
        - cln:
          - start_lightningd &
          - fg
        - lnd:
          - start_lnd &
          - fg
        - cln-gateway:
          - start_cln_gatewayd &
          - fg
        - lnd-gateway:
          - start_lnd_gatewayd &
          - fg
  - federation:
      panes:
        - server-0:
          - start_fedimintd 0
        - server-1:
          - start_fedimintd 1
        - server-2:
          - start_fedimintd 2
        - server-3:
          - start_fedimintd 3
